import assert from 'node:assert/strict';
import fs from 'node:fs';

const tabSource = fs.readFileSync(new URL('../tabs/model-converters-tab.js', import.meta.url), 'utf8');
const pySource = fs.readFileSync(new URL('../converters/scripts/xml_to_cii2019.py', import.meta.url), 'utf8');
const invocationSource = fs.readFileSync(new URL('../converters/invocation-builder.js', import.meta.url), 'utf8');

for (const token of [
  'Create enriched XML before CII',
  '_enrichXmlForCii2019',
  'removedDuplicateSupports',
  'datumNode || restrainedNode || group[0]',
  '_buildStagedSupportIndex',
  'Support Type Mapper',
  'getAllRules()',
  'PipelineReference',
  'pipingClassRegex',
  'pipingClassTokenIndex',
  'boreTokenIndex',
  '_supportTagsFromAttrs',
  '_xmlNodeSupportTags',
  '_enrichment_diagnostics.json',
  'diagnosticText',
  'ps-tag',
  'stagedName',
  'tokenDelimiter',
  'boreTokenIndex',
  'diagnostics.push',
  'createElementNS',
  'npsToDn',
  'masterUrl',
  '_loadXmlCiiWeightMasterRows',
  'model-converters-diagnostics-table',
  'setDiagnosticRows',
  '_diagnosticRowsForTable',
  'weight-master-source',
  'ratingSequence',
  '_findWeightMasterMatch',
  '_collectXmlCiiZeroRigidWeightIssues',
  '_openXmlCiiZeroRigidWeightPopup',
  '_applyXmlCiiRigidWeightOverrides',
  '_xmlCiiDtxrPsForNode',
  '_xmlCiiDtxrPosForNode',
  'DTXR_PS',
  'DTXR_POS',
  'dtxrPsAnnotations',
  'dtxrPosAnnotations',
  'dtxrPositionOffset',
  'rigidWeight',
  '4A Weight Match',
  "t2: 'T2'",
  "t3: 'T3'",
  'Temperature2',
  'Temperature3',
  'Rigid zero-weight review applied',
  'const enriched = await _enrichXmlForCii2019',
  'const diagnosticSource = Array.isArray(enriched?.diagnostics) ? enriched.diagnostics : diagnostics',
  'ElementLengthMm',
  'Rating annotations',
  'weight annotations',
  '_enriched.xml',
  '_xmlCiiApproximateClass',
  '_xmlCiiResolveMaterialCode',
  '_findPipingClassMaster',
  '_loadXmlCiiMaterialMap',
  'class-master-match',
  'WallThickness',
  'CorrosionAllowance',
  'MaterialCode',
  'Piping_class_master.json',
  'PCF_MAT_MAP.TXT',
  'data-popup-tab="regex"',
  'Regex Tester',
  'renderRegexTab',
  'data-popup-regex',
  'data-popup-tab="masters"',
  'renderMastersTab',
  'data-popup-masters',
  'Material Map (code',
  'data-mm-field',
  'data-ov-key',
  'data-popup-tab="logs"',
  'Diagnostics Log',
  'renderLogsTab',
  'materialMethod',
]) {
  assert.ok(tabSource.includes(token), `expected ${token} in Model Converter enriched XML flow`);
}

assert.ok(!pySource.includes('--staged-json'), 'xml_to_cii2019.py must remain a pure XML->CII converter');
assert.ok(!pySource.includes('--support-config-json'), 'xml_to_cii2019.py must not consume enrichment config');
assert.ok(!invocationSource.includes('--staged-json'), 'worker invocation must not pass staged JSON into xml_to_cii2019.py');

console.log('xml-cii-enriched-xml-flow smoke test passed.');
